
keyword_classes = {
    "entity":{"college", "degree", "degreetype", "programme", "course", "seats", "category", "cutoff", "coursefee", "faculty", "department"}, #  "eligibility", "duration", "syllabus"
    "quantifier": {"Number"},    
    "show": {"Show"},
    "details": {"eligibility", "duration", "syllabus"},
    # "faculty": { "Faculty of Arts", "Faculty of Applied Social Sciences and Humanities", "Faculty of Commerce and Business Studies", "Faculty of Education", "Faculty of Interdisciplinary and Life Sciences", "Faculty of Law", "Faculty of Management Studies", "Faculty of Mathematical Sciences", "Faculty of Medical Sciences", "Faculty of Music", "Faculty of Open Learning", "Science", "Faculty of Social Sciences", "Faculty of Technology", "Faculty of Affiliated Faculties" },
    # "department": { "Department of Arabic","Department of English", "Department of Germanic & Romance Studies", "Department of Hindi", "Department of Library & Information Science", "Department of Linguistics", "Department of Modern Indian Languages and Literary Studies", "Department of Persian", "Department of Philosophy", "Department of Psychology", "Department of Slavonic & Finno-Ugrian Studies", "Department of Sanskrit", "Department of Punjabi", "Department of Urdu", "Department of Buddhist Studies" }, # to be discussed
    "college": {"Acharya Narendra Dev College","Aditi Mahavidyalaya(W)", "Aryabhatta College", "Atma Ram Sanatan Dharma College", "Bhagini Nivedita College", "Bharati College", "Daulat Ram College","Bhaskaracharya College Of Applied Sciences", "College Of Vocational Studies", "Deen Dayal Upadhyaya College"},
    # "course": {"bachelor of arts (H) Psychology", "bachelor of sciences (Prog) Physical Science Chemistry", "bachelor of sciences Physical Science With Computer", "bachelor of arts (H) Sanskrit", "bachelor of sciences (H) Instrumentation", "bachelor of sciences (H) Botany", "bachelor of sciences (H) Mathematics", "bachelor of arts (Prog)", "bachelor of sciences Life Science", "bachelor of arts (H) Sociology", "bachelor of sciences (Prog) Applied Physical Science Industrial\nChemistry", "bachelor of sciences (H) Polymer Science", "bachelor of sciences Physical Science With Comp Science", "bachelor of sciences (H) Chemistry", "bachelor of commerce (H)", "bachelor of sciences(H) Computer Science", "BA (H) History", "bachelor of arts (H) English", "BA (H) English", "bachelor of sciences Physical Science With Computer Science", "bachelor of sciences (H) Home Science", "bachelor of sciences Life Sciences", "bachelor of sciences (H) Physics", "bachelor of commerce (Prog)", "bachelor of sciences (H) Zoology", "bachelor of arts (Vs) Office Management And Secretarial Practice", "bachelor of sciences (H) Electronics", "bachelor of arts (H) Economics", "bachelor of arts (Vs) Human Resource Management", "BA (H) Philosophy", "bachelor of sciences (H) Biochemistry", "BA (H) Psychology", "bachelor of arts (Vs) Management And Marketing Of Insurance", "bachelor of arts (Vs) Material Management", "bachelor of sciences (H) Microbiology", "bachelor of arts (Vs) Tourismmanagement", "bachelor of sciences (H) Physics", "bachelor of arts (H) Hindi", "BA (H) Hindi", "bachelor of sciences (H) Chemistry", "bachelor of arts (H) History", "BA (H) Pol Science", "BA (H) Economics", "bachelor of arts (H) Social Work", "bachelor of sciences (H) Computer Science", "bachelor of arts (H) Political Science", "bachelor of sciences  (H) Physics", "bachelor of arts (H) Hindi Journalism", "bachelor of arts (Prog) (History + Political Science)", "bachelor of sciences (H) Biomedical Science", "BA (H) Sanskrit", "bachelor of commerce (H)", "bachelor of commerce", "bachelor of sciences (H) Psychology", "bachelor of sciences (H) Zoology", "bachelor of arts (H) Geography", "bachelor of sciences Physical Science With Chemistry", "bachelor of arts (H) Pol Science", "bachelor of arts (Vs) Marketing Management And Retail Business", "bachelor of arts (H) Journalism", "bachelor of sciences (H) Mathematics", "bachelor of sciences (Prog) Physical Science Electronics", "bachelor of sciences (H) Botany", "BA (H) Music", "bachelor of sciences (H) Food Technology", "bachelor of sciences (Prog) Physical Science Computer Science", "bachelor of sciences Physical Science With Electronics", "bachelor of arts (Vs) Small And Medium Enterprises", "bachelor of sciences Mathematical Science"},
    "degree": {"B.A.", "B.SC.", "B.COM.", "B.VOC.", "B.J.", "B.TECH."},
    "degreetype":{"honours", "program", "pass", "vocational studies"},
    # programme = degree + degreetype + course = ba (h) economics
    "category": {"UR", "OBC", "EWS", "Minority", "SC", "ST", "PWD"}, #, "Total Seats"
    # "course": {"Sanskrit", "English", "Hindi", "Punjabi", "Bengali", "Urdu", "Arabic", "Persian", "French", "German", "Italian", "Spanish", "Applied Psychology", "Psychology", "Philosophy", "Hindi Patrakarita", "Journalism", "Humanities and Social Sciences", "Geography", "History", "Political Science", "Social Work", "Sociology", "Economics", "Multi-Media and Mass Communication", "Program", "Five Year Integrated Program in Journalism", "Anthropology", "Botany", "Biomedical Science", "Chemistry", "Polymer Science", "Electronics", "Environmental Science", "Geology", "Statistics", "Home Science", "Biological Sciences", "Zoology", "Bio-Chemistry", "Physics", "Computer Science", "Instrumentation", "Food Technology", "Mathematics", "Microbiology", "B.Sc (Prog.)Applied Physical Sciences with Analytical Methods in Chemistry & Biochemistry", "Physical Science with Chemistry", "Applied Life Science", "Mathematical Sciences", "Physical Education, Health Education and Sports B.Sc. (PE, HE&S)", "Applied Physical Sciences with Industrial Chemistry", "Physical Science with Electronics", "Physical Science with Computer Science/ Informatics Practices", "Life Science", "Home Science", "Management Studies", "Business Administration in Financial Investment Analysis", "Business Economics", "Information Technology and Mathematical Innovations", "Bachelor of Elementary Education", "B.A. Vocational Studies", "Banking Operations", "Healthcare Management", "Printing Technology", "Retail Management and IT", "Software Development", "Web Designing", "Music: Vocal/ Instrumental Sitar/ Sarod/ Guitar/ Violin/ Santoor)", "Karnatak Music-Vocal/Instrumental (Veena / Violin)", "Hindustani Music: Percussion (Tabla/Pakhawaj)"}
    "course":{"mathematics", "management and marketing of insurance", "chemistry", "human resource management", "history", "physical science with computer science", "zoology", "tourism management", "small and medium enterprises", "geography", "economics", "computer science", "philosophy", "biomedical science", "botany", "life science", "applied physical sciences with industrial", "physics", "microbiology", "marketing management and retail business", "physical science with electronics", "psychology", "food technology", "material management", "music", "social work", "sanskrit", "physical science with chemistry", "hindi journalism", "political science", "electronics", "instrumentation", "computer  science", "d", "office management and secretarial practice", "journalism", "life sciences", "biochemistry", "polymer science", "home science", "sociology", "hindi", "english", "mathematical science"}  #, "link"
    # "hhhh": {"harshita"}
}


