
keyword_classes = {
    "entity":{"faculty", "department", "college", "course", "seats", "category", "eligibility", "duration", "syllabus", "cutoff", "coursefee" },  #"degree", 
    "quantifier": {"Number"},    
    "show": {"List", "Details"},
    "faculty": { "Faculty of Arts", "Faculty of Applied Social Sciences and Humanities", "Faculty of Commerce and Business Studies", "Faculty of Education", "Faculty of Interdisciplinary and Life Sciences", "Faculty of Law", "Faculty of Management Studies", "Faculty of Mathematical Sciences", "Faculty of Medical Sciences", "Faculty of Music", "Faculty of Open Learning", "Science", "Faculty of Social Sciences", "Faculty of Technology", "Faculty of Affiliated Faculties" },
    "department": { "Department of Arabic","Department of English", "Department of Germanic & Romance Studies", "Department of Hindi", "Department of Library & Information Science", "Department of Linguistics", "Department of Modern Indian Languages and Literary Studies", "Department of Persian", "Department of Philosophy", "Department of Psychology", "Department of Slavonic & Finno-Ugrian Studies", "Department of Sanskrit", "Department of Punjabi", "Department of Urdu", "Department of Buddhist Studies" }, # to be discussed
    "college": {"Acharya Narendra Dev College","Aditi Mahavidyalaya(W)", "Aryabhatta College", "Atma Ram Sanatan Dharma College", "Bhagini Nivedita College", "Bharati College", "Daulat Ram College","Bhaskaracharya College Of Applied Sciences", "College Of Vocational Studies", "Deen Dayal Upadhyaya College"},
    "course": {"B.A. (H) Psychology", "B.Sc. (Prog.) Physical Science Chemistry", "B.Sc. Physical Science With Computer", "B.A. (H) Sanskrit", "B.Sc. (H) Instrumentation", "B.Sc (H) Botany", "B.Sc. (H) Mathematics", "B.A. (Prog.)", "B.Sc. Life Science", "B. A (H) Sociology", "B.Sc. (Prog.) Applied Physical Science Industrial\nChemistry", "B.Sc. (H) Polymer Science", "B.Sc. Physical Science With Comp. Science", "B.Sc. (H) Chemistry", "B.Com (H)", "B.Sc.(H) Computer Science", "B.A (H) History", "B.A. (H) English", "B.A (H) English", "B.Sc. Physical Science With Computer Science", "B.Sc. (H) Home Science", "B.Sc. Life Sciences", "B.Sc (H) Physics", "B.Com. (Prog.)", "B.Sc (H) Zoology", "B.A. (Vs) Office Management And Secretarial Practice", "B.Sc. (H) Electronics", "B.A. (H) Economics", "B.A. (Vs) Human Resource Management", "B.A (H) Philosophy", "B.Sc (H) Biochemistry", "B.A (H) Psychology", "B.A. (Vs) Management And Marketing Of Insurance", "B.A. (Vs) Material Management", "B.Sc. (H) Microbiology", "B.A. (Vs) Tourismmanagement", "B.Sc. (H) Physics", "B.A. (H) Hindi", "B.A (H) Hindi", "B.Sc (H) Chemistry", "B.A. (H) History", "B.A (H) Pol. Science", "B.A (H) Economics", "B.A. (H) Social Work", "B.Sc. (H) Computer Science", "B.A. (H) Political Science", "B.Sc.  (H) Physics", "B.A. (H) Hindi Journalism", "B.A. (Prog.) (History + Political Science)", "B.Sc. (H) Biomedical Science", "B.A (H) Sanskrit", "B.Com. (H)", "B.Com.", "B.Sc. (H) Psychology", "B.Sc. (H) Zoology", "B.A. (H) Geography", "B.Sc. Physical Science With Chemistry", "B.A. (H) Pol. Science", "B.A. (Vs) Marketing Management And Retail Business", "B. A. (H) Journalism", "B.Sc (H) Mathematics", "B.Sc. (Prog.) Physical Science Electronics", "B.Sc. (H) Botany", "B.A (H) Music", "B.Sc. (H) Food Technology", "B.Sc. (Prog.) Physical Science Computer Science", "B.Sc. Physical Science With Electronics", "B.A. (Vs) Small And Medium Enterprises", "B.Sc. Mathematical Science"},
    "category": {"General", "SC", "ST", "OBC", "Minority", "EWS", "Total Seats"}, 
    
}
