synonyms = {

    "BSc": ["bsc", "bachelor of sciences", "bachelor of science", "B Sc"," bsc"],
    "BA": ["ba", "bachelor of arts", "bachelor of art", "b a"],
    "Economics": ["economics", "economic", "economy"],
    "History": ["history"],
    ""

    # "Seat Matrix": ["seat", "seat matrix", "seat allocation", "allocation", "seats", "seats", "seats"],
    "General": ["genr", "gen", "general", "ur", "unreserved"],
    "SC": ["sc", "scheduled cast", "scheduled caste", "schedule cast", "schedule caste"],
    "ST": ["st", "scheduled tribe", "scheduled trib", "schedule tribe", "schedule trib"],
    "EWS": ["economically weaker section", "ews", "financially weaker class", "weaker class", "financially weaker section", "economically poor section", "economically poor class"],
    "OBC": ["obc", "other backward class" ,"economically backward class" ,"backward class"],
    "Minority": ["minority"],
    # "Course": ["course", "courses"],
    "Hindi": ["hindi"], 
    "English": ["english"],
    "Sanskrit": ["sanskrit"],
    "Punjabi": ["punjabi"],
    "Bengali": ["bengali"],
    "Urdu": ["urdu"],
    "Arabic": ["arabic"],
    "Persian": ["Persian"],
    "French": ["french"], 
    "German": ["german"],
    "Italian": ["italian"], 
    "Spanish": ["spanish"],
    "Acharya Narendra Dev College": ["acharya narendra dev college", "acharya narendra dev", "andc", "acharya narendra", "acharya narender dev college", "acharya dev college", "acharya dev"],
    "Aditi Mahavidyalaya(W)": ["aditi mahavidyalaya", "aditi college", "aditi"],
    "Aryabhatta College": ["aryabhatta", "aryabhat", "aryabat"],    
    "Atma Ram Sanatan Dharma College": ["atma ram sanatan dharma college", "arsd"],
    "Bhagini Nivedita College": ["bhagini nivedita college", "bhagini navedita college"],
    "Bharati College": ["bharati college", "bharti", "bhrti", "bhaarti", "bhaarati college"],
    
    "Arts":["arts", "art"],
    "Applied Social Sciences and Humanities":[],
    "Commerce and Business Studies":[],
    "Education":[],
    "Interdisciplinary and Life Sciences":[],
    "Law":[],
    "Management Studies":[],
    "Mathematical Sciences":[],
    "Medical Sciences":[],
    "Music":[],
    "Open Learning":[],
    "Science":[],
    "Social Sciences":[],
    "Technology":[],
    "Affiliated Faculties":[],

    "Department of Arabic": ["department of arabic"],
    "Department of English": [], 
    "Department of Germanic & Romance Studies": [], 
    "Department of Hindi": [], 
    "Department of Library & Information Science": [], 
    "Department of Linguistics": [],
    "Department of Modern Indian Languages and Literary Studies": [], 
    "Department of Persian": [], 
    "Department of Philosophy": [],
    "Department of Psychology": [], 
    "Department of Slavonic & Finno-Ugrian Studies": [], 
    "Department of Sanskrit": [], 
    "Department of Punjabi": [], 
    "Department of Urdu": [], 
    "Department of Buddhist Studies": []



   
}
