synonyms = {

    "BSc": ["bsc", "bachelor of sciences", "bachelor of science", "B Sc"," bsc"],
    "BA": ["ba", "bachelor of arts", "bachelor of art", "b a"],
    "Economics": ["economics", "economic", "economy"],
    "History": ["history"],
    # "Seat Matrix": ["seat", "seat matrix", "seat allocation", "allocation", "seats", "seats", "seats"],
    "General": ["genr", "gen", "general", "ur", "unreserved"],
    "SC": ["sc", "scheduled cast", "scheduled caste", "schedule cast", "schedule caste"],
    "ST": ["st", "scheduled tribe"],
    "EWS": ["economically weaker section", "ews"],
    "Minority": ["minority"],
    "Course": ["course"],
    "Hindi": [ "hindi", ("hin")],
    "English": ["english", ("eng", "englis", "engl")],
    "Sanskrit": ["sanskrit", ("Sans")],
    "Punjabi": ["punjabi"],
    "Bengali": ["bengali"],
    "Urdu": ["urdu"],
    "Arabic": ["arabic"],
    "French": ["french"], 
    "German": ["german"],
    "Italian": ["italian"], 
    "Spanish": ["spanish"],
    
}
