synonyms = {

    "BSc": ["bsc", "bachelor of sciences", "bachelor of science", "B Sc"," bsc"],
    "BA": ["ba", "bachelor of arts", "bachelor of art", "b a"],
    "Economics": ["economics", "economic", "economy"],
    "History": ["history"],
    "Number": ["number" , "how many", "how much", "what are the number", "what are the no.", "get me the number"],
    "List": ["list", "names", "name", "what", " what are", "name the", "list the"], #why plural we are using the lem and for spell
    "Details": ["details"],
    # "Seat Matrix": ["seat", "seat matrix", "seat allocation", "allocation", "seats", "seats", "seats"],
    "General": ["genr", "gen", "general", "ur", "unreserved"],
    "SC": ["sc", "scheduled cast", "scheduled caste", "schedule cast", "schedule caste"],
    "ST": ["st", "scheduled tribe", "scheduled trib", "schedule tribe", "schedule trib"],
    "EWS": ["economically weaker section", "ews", "financially weaker class", "weaker class", "financially weaker section", "economically poor section", "economically poor class"],
    "OBC": ["obc", "other backward class" ,"economically backward class" ,"backward class"],
    "Minority": ["minority"],
    # "Course": ["course", "courses"],
    "Hindi": ["hindi"], 
    "English": ["english"],
    "Sanskrit": ["sanskrit"],
    "Punjabi": ["punjabi"],
    "Bengali": ["bengali"],
    "Urdu": ["urdu"],
    "Arabic": ["arabic"],
    "Persian": ["persian"],
    "French": ["french"], 
    "German": ["german"],
    "Italian": ["italian"], 
    "Spanish": ["spanish"],
    "Acharya Narendra Dev College": ["acharya narendra dev college", "acharya narendra dev", "andc", "acharya narendra", "acharya narender dev college", "acharya dev college", "acharya dev"],
    "Aditi Mahavidyalaya(W)": ["aditi mahavidyalaya", "aditi college", "aditi"],
    "Aryabhatta College": ["aryabhatta", "aryabhat", "aryabat"],    
    "Atma Ram Sanatan Dharma College": ["atma ram sanatan dharma college", "arsd"],
    "Bhagini Nivedita College": ["bhagini nivedita college", "bhagini navedita college", "BNC"],
    "Bharati College": ["bharati college", "bharti", "bhrti", "bhaarti", "bhaarati college"],
    "Daulat Ram College": ["daulat ram college", "drm", "daulat ram", "daulat", "dolat ram", "daulat raam"],
    "Bhaskaracharya College Of Applied Sciences": ["bhaskaracharya college of applied sciences", "bcas", "bhaskaracharya", "bhaskarcharya", "bhaskaracharya college of applied science", "bhaskaracharya college of sciences", "bhaskaracharya science college"],
    "College Of Vocational Studies": ["college of vocational studies", "cvs", "vocational studies college", "college vocational studies", "college of vocational study"],
    "Deen Dayal Upadhyaya College": ["deen dayal upadhyaya college", "dduc", "deen dayal college", "deen dyal college", "deen dyal upadhyaya college", "deen dyal upadhya college"],


    "Faculty of Arts": ["Faculty of Arts", "arts", "art"],
    "Faculty of Applied Social Sciences and Humanities": ["Faculty of Applied Social Sciences and Humanities", "applied social sciences and humanities"],
    "Faculty of Commerce and Business Studies": ["Faculty of Commerce and Business Studies", "commerce and business studies"],
    "Faculty of Education":["Faculty of Education", "education"],
    "Faculty of Interdisciplinary and Life Sciences": ["Faculty of Interdisciplinary and Life Sciences", "Interdisciplinary and Life Sciences"],
    "Faculty of Law": ["Faculty of Law", "law"],
    "Faculty of Management Studies": ["Faculty of Management Studies", "management studies"],
    "Faculty of Mathematical Sciences": ["Faculty of Mathematical Sciences", "mathematical sciences"],
    "Faculty of Medical Sciences": ["Faculty of Medical Sciences", "medical sciences"],
    "Faculty of Music": ["Faculty of Music", "music"],
    "Faculty of Open Learning":["Faculty of Open Learning", "open learning"],
    "Faculty of Science":["Faculty of Science", "science"],
    "Faculty of Social Sciences":["Faculty of Social Sciences", "social science"],
    "Faculty of Technology": ["Faculty of Technology", "technology"],
    "Affiliated Faculties": ["affiliated faculties", "other faculties", "other faculty"],

    "Department of Arabic": ["department of arabic"],
    "Department of English": ["department of english"], 
    "Department of Germanic & Romance Studies": ["department of germanic & romance studies"], 
    "Department of Hindi": ["department of hindi"], 
    "Department of Library & Information Science": ["department of library & information science"], 
    "Department of Linguistics": ["department of linguistics"],
    "Department of Modern Indian Languages and Literary Studies": ["department of modern indian languages and literary studies"], 
    "Department of Persian": ["department of persian"], 
    "Department of Philosophy": ["department of philosophy"],
    "Department of Psychology": ["department of psychology"], 
    "Department of Slavonic & Finno-Ugrian Studies": ["department of slavonic & finno-ugrian studies"], 
    "Department of Sanskrit": ["department of sanskrit"], 
    "Department of Punjabi": ["department of punjabi"], 
    "Department of Urdu": ["department of urdu"], 
    "Department of Buddhist Studies": ["department of buddhist studies"],

    "degree": ["degree", "degre", "dgree"], 
    "faculty": ["faculty", "faclty", "faculty"], 
    "department": ["department", "dept", "deprtmnt", "departments", "department"], 
    "college": ["clg", "college", "colleg", "collg", "college"],
    "course" : ["course", "crse", "courses", "corse"], 
    "seats": ["seats", "seat", "sts"], 
    "category": ["categry", "catgory", "categories", "category"], 
    "eligibility": ["eligibility", "elgblity", "eligible", "elagabale", "elgible"], 
    "duration": ["duration", "time period", "how much long", "how many years to complete theis course" ], 
    "syllabus": ["syllabus", "slybus", "sylbus"], 
    "cutoff": ["cutoff"], 
    "coursefee" : ["coursefee"],

   "B.Sc. (Prog.) Physical Science Electronics":["b.sc. (prog.) physical science electronics"], 
   "B.A. (Vs) Management And Marketing Of Insurance": ["b.a. (vs) management and marketing of insurance"], 
   "B.A. (H)Economics": ["b.a. (h)economics"], 
   "B.A. (H) Social Work":["b.a. (h) social work"], 
   "B.A. (H) Psychology":["b.a. (h) psychology"], 
   "B.Sc. Physical Science With Electronics":["b.sc. physical science with electronics"], 
   "B.Sc. Life Sciences":["b.sc. life sciences"], 
   "B.A. (Vs) Marketing Management And Retail Business":["b.a. (vs) marketing management and retail business"], 
   "B.Sc. (H) Mathematics":["b.sc. (h) mathematics", "b.sc (h) maths"], 
   "B.A. (H) Philosophy":["b.a. (h) philosophy"], 
   "B.Sc. (Prog.) Physical Science with Computer Science":["b.sc. (prog.) physical science with computer science"], 
   "B.Sc. (Prog.) Applied Physical Science Industrial Chemistry":["b.sc. (prog.) applied physical science industrial chemistry"], 
   "B.Sc. (H) Microbiology":["b.sc. (h) microbiology"], 
   "B.Sc. Physical Science With Computer Science":[ "b.sc. physical science with computer science"], 
   "B.A. (H) Geography":["b.a. (h) geography"], 
   "B.Sc. Physical Science With Computer Science":["b.sc. physical science with computer science"], 
   "B.A. (Vs)Material Management":["b.a. (vs)material management"], 
   "B.Sc. (H) Polymer Science": ["b.sc. (h) polymer science"], 
   "B.A. (H) Hindi Journalism": ["b.a. (h) hindi journalism"], 
   "B.Sc. (H) Psychology": ["b.sc. (h) psychology"], 
   "B.A. (Vs)Tourism management":["b.a. (vs)tourism management"], 
   "B.A. (H) History":["b.a. (h) history"], 
   "B.Sc. (H) Instrumentation":["b.sc. (h) instrumentation"], 
   "B.A. (Vs) Small And Medium Enterprises":["b.a. (vs) small and medium enterprises"], 
   "B.Sc. Physical Science With Chemistry":["b.sc. physical science with chemistry"], 
   "B.A. (H) Sanskrit": ["b.a. (h) sanskrit"], 
   "B.A. (H) Music": ["b.a. (h) music"], 
   "B.Sc. (H) Food Technology": ["b.sc. (h) food technology"], 
   "B.A. (H) English": ["b.a. (h) english"], 
   "B.Com (Prog.)": ["b.com (prog.)"], 
   "B.Sc. (H) Home Science": [],
   "B.Com.": [], 
   "B.Sc. Physical Science With Computer Science": [], 
   "B.A. (Vs) Human Resource Management": [], 
   "B.A. Prog.": [], 
   "B.A. (H) Economics": [], 
   "B.Sc. (H) Chemistry": [], 
   "B.Com (H)": [], 
   "B.A. (H) Political Science": [], 
   "B. Com. (H)": [], 
   "B.Sc. (H) Biochemistry": [], 
   "B.Sc. Mathematical Science": [], 
   "B.Sc.(H) Mathematics": [], 
   "B.Sc. (H) Computer Science": [], 
   "B. Com.(H)": [], 
   "B.A. (H) Pol. Science": [], 
   "B. A (H) Sociology": [], 
   "B.Sc. Life Science": ["b.sc. life science"], 
   "B.Sc. (H) Botany": [], 
   "B.A. (Prog.) (History + Political Science)": [], 
   "B.Sc. (H) Physics": [], 
   "B.A. (Vs) Office Management And Secretarial Practice": [], 
   "B.Sc.(H) Computer Science": [], 
   "B.A. (H) Hindi": [], 
   "B.Sc. (Prog.) Physical Science Chemistry": [], 
   "B.A. (H) Journalism": [], 
   "B.Sc. (H) Electronics": [], 
   "B.A. (Prog.)": [], 
   "B.Sc. (H) Zoology": [], 
   "B.Sc. (H) Computer  Science": [], 
   "B.Com. (H)": [], 
   "B.Sc. (H) Biomedical Science":[], 
   "B.Com. (H)":[], 
   "B. Com.":[]
    

}
